"""Add delivery agent and order assignment fields

Revision ID: a909e83c90c9
Revises: e6e8fd314e8d
Create Date: 2026-02-03 20:41:47.205009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a909e83c90c9'
down_revision = 'e6e8fd314e8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create enum type for PaymentPhoneChangeStatus
    payment_phone_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentphonechangestatus')
    payment_phone_status_enum.create(op.get_bind(), checkfirst=True)

    op.create_table('delivery_agent_profiles',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('vehicle_type', sa.String(length=50), nullable=True),
    sa.Column('vehicle_registration', sa.String(length=20), nullable=True),
    sa.Column('assigned_zones', sa.JSON(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.Column('total_deliveries', sa.Integer(), nullable=False),
    sa.Column('total_cod_collected', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cod_collected_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('cod_collected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cod_amount_collected', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('cod_verified_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('cod_verified_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('assigned_delivery_agent', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_orders_assigned_delivery_agent'), ['assigned_delivery_agent'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['assigned_delivery_agent'], ['id'])

    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payment_phone_pending', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_change_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentphonechangestatus'), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_change_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_change_reviewed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_change_reviewed_by', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('payment_phone_change_reason', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_profiles', schema=None) as batch_op:
        batch_op.drop_column('payment_phone_change_reason')
        batch_op.drop_column('payment_phone_change_reviewed_by')
        batch_op.drop_column('payment_phone_change_reviewed_at')
        batch_op.drop_column('payment_phone_change_requested_at')
        batch_op.drop_column('payment_phone_change_status')
        batch_op.drop_column('payment_phone_pending')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_orders_assigned_delivery_agent'))
        batch_op.drop_column('assigned_delivery_agent')
        batch_op.drop_column('cod_verified_at')
        batch_op.drop_column('cod_verified_by')
        batch_op.drop_column('cod_amount_collected')
        batch_op.drop_column('cod_collected_at')
        batch_op.drop_column('cod_collected_by')

    op.drop_table('delivery_agent_profiles')

    # Drop enum type
    payment_phone_status_enum = sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='paymentphonechangestatus')
    payment_phone_status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
