"""Add delivery zone requests table

Revision ID: cc7c498fd4ec
Revises: b123456789ab
Create Date: 2026-02-04 09:57:57.884633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7c498fd4ec'
down_revision = 'b123456789ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_zone_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('delivery_agent_id', sa.String(length=36), nullable=False),
    sa.Column('zone_id', sa.String(length=36), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='zonerequeststatus'), nullable=False),
    sa.Column('admin_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['delivery_agent_id'], ['delivery_agent_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['delivery_zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_payouts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('delivery_payouts_payout_number_key'), type_='unique')
        batch_op.drop_index(batch_op.f('ix_delivery_payouts_status'))
        batch_op.drop_index(batch_op.f('ix_delivery_payouts_payout_number'))
        batch_op.create_index(batch_op.f('ix_delivery_payouts_payout_number'), ['payout_number'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_payouts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_payouts_payout_number'))
        batch_op.create_index(batch_op.f('ix_delivery_payouts_payout_number'), ['payout_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_payouts_status'), ['status'], unique=False)
        batch_op.create_unique_constraint(batch_op.f('delivery_payouts_payout_number_key'), ['payout_number'], postgresql_nulls_not_distinct=False)

    op.drop_table('delivery_zone_requests')
    # ### end Alembic commands ###
