"""Fix supplier_payout foreign key to supplier_profiles

Revision ID: e6e8fd314e8d
Revises: a01839534eac
Create Date: 2026-02-03 02:01:14.544212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6e8fd314e8d'
down_revision = 'a01839534eac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payouts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('supplier_payouts_supplier_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'supplier_profiles', ['supplier_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('supplier_payouts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('supplier_payouts_supplier_id_fkey'), 'users', ['supplier_id'], ['id'])

    # ### end Alembic commands ###
